import {env} from 'cloudflare:workers';
import {cookies,headers} from 'next/headers';
import {Day,shiftDate} from './metrics';
export type Config={GOOGLE_CLIENT_ID?:string;GOOGLE_CLIENT_SECRET?:string;SESSION_SECRET?:string;APP_ORIGIN?:string};
export function config(){return env as unknown as Config}
export function configured(){const c=config();return !!(c.GOOGLE_CLIENT_ID&&c.GOOGLE_CLIENT_SECRET&&c.SESSION_SECRET&&c.APP_ORIGIN)}
export async function identity(){return (await headers()).get('oai-authenticated-user-id')}
const enc=new TextEncoder();const dec=new TextDecoder();
function base64(b:Uint8Array){return btoa(String.fromCharCode(...b)).replaceAll('+','-').replaceAll('/','_').replaceAll('=','')}
function bytes(s:string){return Uint8Array.from(atob(s.replaceAll('-','+').replaceAll('_','/')),c=>c.charCodeAt(0))}
async function key(){const s=config().SESSION_SECRET;if(!s)throw Error('not_configured');return crypto.subtle.importKey('raw',await crypto.subtle.digest('SHA-256',enc.encode(s)),{name:'AES-GCM'},false,['encrypt','decrypt'])}
export async function seal(value:unknown){const iv=crypto.getRandomValues(new Uint8Array(12));const data=await crypto.subtle.encrypt({name:'AES-GCM',iv},await key(),enc.encode(JSON.stringify(value)));return base64(iv)+'.'+base64(new Uint8Array(data))}
export async function unseal<T>(value:string):Promise<T|null>{try{const [iv,data]=value.split('.');return JSON.parse(dec.decode(await crypto.subtle.decrypt({name:'AES-GCM',iv:bytes(iv)},await key(),bytes(data))))}catch{return null}}
export const cookieOptions={httpOnly:true,secure:true,sameSite:'lax' as const,path:'/'};
export type Session={uid:string;access:string;refresh?:string;expires:number;until:number};
export async function getSession(){const uid=await identity();const raw=(await cookies()).get('pulse-session')?.value;if(!raw||!uid)return null;const s=await unseal<Session>(raw);return s&&s.uid===uid&&s.until>Date.now()?s:null}
export async function tokenRequest(params:Record<string,string>){const c=config();const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({...params,client_id:c.GOOGLE_CLIENT_ID!,client_secret:c.GOOGLE_CLIENT_SECRET!}),signal:AbortSignal.timeout(15000)});if(!r.ok)throw Error('reauthorize');const j=await r.json() as {access_token:string;refresh_token?:string;expires_in:number};if(!j.access_token)throw Error('reauthorize');return j}
export async function accessSession(s:Session){if(s.expires>Date.now()+60000)return s;if(!s.refresh)throw Error('reauthorize');const t=await tokenRequest({grant_type:'refresh_token',refresh_token:s.refresh});const next={...s,access:t.access_token,refresh:t.refresh_token??s.refresh,expires:Date.now()+t.expires_in*1000};await saveSession(next);return next}
export async function saveSession(s:Session){(await cookies()).set('pulse-session',await seal(s),{...cookieOptions,maxAge:Math.max(0,Math.floor((s.until-Date.now())/1000))})}
export function sameOrigin(req:Request){return !!config().APP_ORIGIN&&req.headers.get('origin')===config().APP_ORIGIN}
// Only a fixed list of read-only Google data types can be fetched by the server.
export const specs=[['daily-heart-rate-variability','daily_heart_rate_variability.date','dailyHeartRateVariability'],['daily-resting-heart-rate','daily_resting_heart_rate.date','dailyRestingHeartRate'],['sleep','sleep.interval.civil_end_time','sleep'],['exercise','exercise.interval.civil_start_time','exercise']] as const;
type Point=Record<string,any>; // Provider JSON is checked field-by-field at the normalization boundary.
export async function readPoints(access:string,type:string,field:string,start:string,end:string){const points:Point[]=[];let page='';for(let i=0;i<100;i++){const u=new URL(`https://health.googleapis.com/v4/users/me/dataTypes/${type}/dataPoints`);u.searchParams.set('filter',`${field} >= "${start}" AND ${field} < "${end}"`);u.searchParams.set('pageSize',type==='sleep'||type==='exercise'?'25':'1000');if(page)u.searchParams.set('pageToken',page);const r=await fetch(u,{headers:{Authorization:`Bearer ${access}`},signal:AbortSignal.timeout(15000)});if(!r.ok)throw Error(`${type}: ${r.status}`);const data=await r.json() as {dataPoints?:Point[];nextPageToken?:string};points.push(...(data.dataPoints??[]));page=data.nextPageToken??'';if(!page)return points;}throw Error(`${type}: pagination_limit`)}
function dateKey(d:any){return d?.year&&d?.month&&d?.day?`${d.year}-${String(d.month).padStart(2,'0')}-${String(d.day).padStart(2,'0')}`:''}
function sessionDate(i:any,end=false){const civil=end?i?.civilEndTime:i?.civilStartTime;const fromCivil=dateKey(civil?.date);if(fromCivil)return fromCivil;const time=end?i?.endTime:i?.startTime;const offset=parseFloat((end?i?.endUtcOffset:i?.startUtcOffset)??'0');const t=Date.parse(time)+offset*1000;return Number.isFinite(t)?new Date(t).toISOString().slice(0,10):''}
function num(n:unknown){if(n===null||n===undefined||n==='')return null;const v=Number(n);return Number.isFinite(v)&&v>=0?v:null}
export function normalize(end:string,results:PromiseSettledResult<Point[]>[]){const days:Day[]=Array.from({length:56},(_,i)=>({date:shiftDate(end,i-55),hrv:null,rhr:null,sleep:null,workouts:[],activityAvailable:results[3]?.status==='fulfilled'}));const byDate=new Map(days.map(d=>[d.date,d]));const warnings:string[]=[];results.forEach((result,index)=>{if(result.status==='rejected'){warnings.push(`${['HRV','Resting heart rate','Sleep','Workouts'][index]} could not be retrieved. Check permissions and try syncing again.`);return}const seen=new Set<string>();for(const p of result.value){const v=p[specs[index][2]];if(!v)continue;const fingerprint=p.name??JSON.stringify(v);if(seen.has(fingerprint))continue;seen.add(fingerprint);const date=index<2?dateKey(v.date):sessionDate(v.interval,index===2);const d=byDate.get(date);if(!d)continue;if(index===0&&d.hrv===null)d.hrv=num(v.averageHeartRateVariabilityMilliseconds);if(index===1&&d.rhr===null)d.rhr=num(v.beatsPerMinute);if(index===2){const m=num(v.summary?.minutesAsleep);if(m!==null)d.sleep=(d.sleep??0)+m;}if(index===3){const minutes=v.activeDuration?parseFloat(v.activeDuration)/60:(Date.parse(v.interval?.endTime)-Date.parse(v.interval?.startTime))/60000;if(Number.isFinite(minutes)&&minutes>=0)d.workouts.push({name:String(v.displayName??v.exerciseType??'Workout'),minutes})}}});return {days,warnings}}
